# Add api to workspace
# https://github.com/moringaman/deskfruit-api.git
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

additionalRepositories:
  - url: https://github.com/moringaman/deskfruit-api
    checkoutLocation: backend

workspaceLocation: frontend/gitpod-ws.code-workspace
checkoutLocation: frontend
tasks:
  - name: "backend"
    # change working directory as per configured in `checkoutLocation`
    # which is configured above as `/workspaces/backend`
    before: |
      cd ../backend
    init: |
      yarn
    command: |
      yarn start:dev
  - name: "frontend"
    init: npm install
    command: npm run start
ports:
  - name: Backend Api
    description: This is the main application backend
    port: 3001
    visibility: public
    onOpen: ignore

  - name: Web App
    port: 3000
    description: Main front end application
    visibility: public
    onOpen: open-preview
