# Add api to workspace
# https://github.com/moringaman/deskfruit-api.git

additionalRepositories:
  - url: https://github.com/moringaman/deskfruit-api
    checkoutLocation: backend

workspaceLocation: frontend/gitpod-ws.code-workspace
checkoutLocation: frontend
tasks:
  - name: "backend"
    # change working directory as per configured in `checkoutLocation`
    # which is configured above as `/workspaces/backend`
    before: |
      cd ../backend
    init: |
      yarn
    command: |
      yarn start:dev
  - name: "frontend"
    init: npm install && npm run build
    command: npm run start
ports:
  - name: Backend Api
    description: This is the main application backend
    port: 3000
    visibility: public
    onOpen: ignore

  - name: Web App
    port: 9090
    description: Main front end application
    visibility: public
    onOpen: open-preview
