export { default as TodosPage} from './TodosPage'
export { default as DeskPage} from './DeskPage'
export { default as HomePage} from './HomePage'
export { default as AuthPage} from './AuthPage'
export { default as ProfilePage } from './ProfilePage'
